### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by TheEibwen** [all-rit/AccessibilityLab1#35]
The scoring system still needs some tweaks, as one still can try to click quickly in the second playthrough and get a higher score compared to the first and third playthroughs.

Plans are to:
- Increase the number of points subtracted from an incorrect answer.
- Lock boxes longer if there is no hint available.

**Comment by Boggartfly** [comment]
How are we doing on this?

**Comment by TheEibwen** [comment]
Already fixed, closing now
