### ISSUE TITLE
Update Audio Cue

### ISSUE THREAD

**Issue by TheEibwen** [all-rit/AccessibilityLab1#9]
Currently, the audio cue uses a buzz sound. It is too loud and lasts a little longer than expected. The audio cue should be changed to something else, perhaps it could say "There's a hint!" instead of a buzz sound.

**Comment by TheEibwen** [comment]
@scioffi @saf6260 

Is it possible for either of you to help me out with this issue? ^^

**Comment by scioffi** [comment]
I am working on this right now. I got an audio clipping today but the person couldn't stop laughing when doing it (2nd one to do this). I will get a new one for you soon.
